{
 "title": "IPFS performance",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Local Transfer",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "milliseconds" }
   ],
   "targets": [
    {
     "alias": "small file - empty repo",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "localTransfer",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "js-ipfs" },
      { "condition": "AND", "key": "testClass", "operator": "=", "value": "smallfile" },
      { "condition": "AND", "key": "subTest", "operator": "=", "value": "empty-repo" }
     ]
    },
    {
     "alias": "large file - empty repo",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "localTransfer",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "js-ipfs" },
      { "condition": "AND", "key": "testClass", "operator": "=", "value": "largefile" },
      { "condition": "AND", "key": "subTest", "operator": "=", "value": "empty-repo" }
     ]
    },
    {
     "alias": "large file - populated repo",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "localTransfer",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "js-ipfs" },
      { "condition": "AND", "key": "testClass", "operator": "=", "value": "largefile" },
      { "condition": "AND", "key": "subTest", "operator": "=", "value": "populated-repo" }
     ]
    },
    {
     "alias": "small file - populated repo",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "localTransfer",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "js-ipfs" },
      { "condition": "AND", "key": "testClass", "operator": "=", "value": "smallfile" },
      { "condition": "AND", "key": "subTest", "operator": "=", "value": "populated-repo" }
     ]
    }
   ]
  },
  {
   "title": "Local Add",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Empty Repo - large file",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "unixFsAdd",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "subTest", "operator": "=", "value": "empty-repo" },
      { "condition": "AND", "key": "testClass", "operator": "=", "value": "largefile" }
     ]
    },
    {
     "alias": "Empty Repo - small file",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "unixFsAdd",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "subTest", "operator": "=", "value": "empty-repo" },
      { "condition": "AND", "key": "testClass", "operator": "=", "value": "smallfile" }
     ]
    },
    {
     "alias": "Populated Repo - small file",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "unixFsAdd",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "subTest", "operator": "=", "value": "populated-repo" },
      { "condition": "AND", "key": "testClass", "operator": "=", "value": "smallfile" }
     ]
    },
    {
     "alias": "Populated Repo - large file",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "unixFsAdd",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "subTest", "operator": "=", "value": "populated-repo" },
      { "condition": "AND", "key": "testClass", "operator": "=", "value": "largefile" }
     ]
    }
   ]
  },
  {
   "title": "Local Extract",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "milliseconds" }
   ],
   "targets": [
    {
     "alias": "small file - empty repo",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "localExtract",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "js-ipfs" },
      { "condition": "AND", "key": "testClass", "operator": "=", "value": "smallfile" },
      { "condition": "AND", "key": "subTest", "operator": "=", "value": "empty-repo" }
     ]
    },
    {
     "alias": "large file - empty repo",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "localExtract",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "js-ipfs" },
      { "condition": "AND", "key": "testClass", "operator": "=", "value": "largefile" },
      { "condition": "AND", "key": "subTest", "operator": "=", "value": "empty-repo" }
     ]
    },
    {
     "alias": "large file - populated repo",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "localExtract",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "js-ipfs" },
      { "condition": "AND", "key": "testClass", "operator": "=", "value": "largefile" },
      { "condition": "AND", "key": "subTest", "operator": "=", "value": "populated-repo" }
     ]
    },
    {
     "alias": "small file - populated repo",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "localExtract",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "js-ipfs" },
      { "condition": "AND", "key": "testClass", "operator": "=", "value": "smallfile" },
      { "condition": "AND", "key": "subTest", "operator": "=", "value": "populated-repo" }
     ]
    }
   ]
  },
  {
   "title": "Multi Peer Transfer",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "milliseconds" }
   ],
   "targets": [
    {
     "alias": "small file - empty repo",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "multiPeerTransfer",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "js-ipfs" },
      { "condition": "AND", "key": "testClass", "operator": "=", "value": "smallfile" },
      { "condition": "AND", "key": "subTest", "operator": "=", "value": "empty-repo" }
     ]
    },
    {
     "alias": "large file - empty repo",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "multiPeerTransfer",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "js-ipfs" },
      { "condition": "AND", "key": "testClass", "operator": "=", "value": "largefile" },
      { "condition": "AND", "key": "subTest", "operator": "=", "value": "empty-repo" }
     ]
    },
    {
     "alias": "large file - populated repo",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "multiPeerTransfer",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "js-ipfs" },
      { "condition": "AND", "key": "testClass", "operator": "=", "value": "largefile" },
      { "condition": "AND", "key": "subTest", "operator": "=", "value": "populated-repo" }
     ]
    },
    {
     "alias": "small file - populated repo",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "multiPeerTransfer",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "js-ipfs" },
      { "condition": "AND", "key": "testClass", "operator": "=", "value": "smallfile" },
      { "condition": "AND", "key": "subTest", "operator": "=", "value": "populated-repo" }
     ]
    }
   ]
  }
 ]
}